after-login-command = []
after-startup-command = [
  # 'exec-and-forget borders active_color=0xff34a1eb inactive_color=0xff000000 width=8.0'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 0
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 0
    inner.vertical =   0
    outer.left =       0
    outer.bottom =     0
    outer.top =        0
    outer.right =      0

[mode.main.binding]
    cmd-enter = 'exec-and-forget /opt/homebrew/bin/alacritty'
    cmd-b = 'exec-and-forget open -a "/Applications/Google Chrome.app"'
    cmd-z = 'exec-and-forget /opt/homebrew/bin/alacritty -e vifm'
    cmd-n = 'exec-and-forget /opt/homebrew/bin/alacritty -e nvim'
    cmd-r = ['reload-config', 'mode main']
    cmd-t = 'layout tiles horizontal vertical'
    cmd-slash = 'layout accordion horizontal vertical'
    cmd-m = 'layout tiles accordion'
    cmd-f = 'layout tiling floating'
    cmd-backtick = 'workspace-back-and-forth'

    cmd-h = 'exec-and-forget ~/.local/bin/aerospace-prev-non-empty-workspace'
    cmd-j = 'focus dfs-next --boundaries-action wrap-around-the-workspace'
    cmd-k = 'focus dfs-prev --boundaries-action wrap-around-the-workspace'
    cmd-l = 'exec-and-forget ~/.local/bin/aerospace-next-non-empty-workspace'
    cmd-u = 'workspace --wrap-around prev'
    cmd-i = 'workspace --wrap-around next'

    # cmd-shift-h = 'move left'
    # cmd-shift-l = 'move right'
    cmd-shift-j = 'move down'
    cmd-shift-k = 'move up'
    cmd-shift-x = ['close-all-windows-but-current', 'close', 'mode main']

    cmd-minus = 'resize smart -50'
    cmd-equal = 'resize smart +50'

    cmd-1 = 'workspace 1'
    cmd-2 = 'workspace 2'
    cmd-3 = 'workspace 3'
    cmd-4 = 'workspace 4'
    cmd-5 = 'workspace 5'

    cmd-shift-1 = 'move-node-to-workspace 1'
    cmd-shift-2 = 'move-node-to-workspace 2'
    cmd-shift-3 = 'move-node-to-workspace 3'
    cmd-shift-4 = 'move-node-to-workspace 4'
    cmd-shift-5 = 'move-node-to-workspace 5'
    cmd-shift-l = 'move-node-to-workspace next --wrap-around'
    cmd-shift-h = 'move-node-to-workspace prev --wrap-around'

    cmd-shift-semicolon = 'mode service'

[mode.service.binding]
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    h = ['join-with left', 'mode main']
    j = ['join-with down', 'mode main']
    k = ['join-with up', 'mode main']
    l = ['join-with right', 'mode main']
