#!/bin/sh

refresh_workspaces() {
    workspaces="$(bspc query -D --names)"
    focused="$(bspc query -D -d --names)"
    output=""

    for workspace in $workspaces; do
    	if [ "$workspace" = "$focused" ]; then
		output="$output <span bgcolor=\"#0054fc\"> $workspace </span>"
	else
		output="$output <span> $workspace </span>"	
	fi
    done

    echo "$output"
}

refresh_workspaces

bspc subscribe desktop | while read -r line; do
	refresh_workspaces
done
