#!/usr/bin/env bash

killall -q numlockx &
killall -q feh &
killall -q yabar; yabar &
killall -q bspwmdesktops &

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
setxkbmap -layout "us,il" -option "grp:alt_shift_toggle" &
numlockx &
~/.fehbg &
urxvtd -q -o -f &
