theme = "dracula"

[editor]
auto-format = true
line-number = "relative"
mouse = false
color-modes = true
cursorline = true
scrolloff = 999
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true

[editor.statusline]
left = ["mode", "file-name"]
center = ["spinner"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"