#! /bin/sh

bspc monitor -d 1 2 3 4 5
bspc config border_width        5
bspc config window_gap          0

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#000000"
bspc config focused_border_color  "#03A9F4"
bspc config presel_feedback_color "#C57E8700"

for i in {1..5}
do
  bsp-layout set tall "$i" -- --master-size 0.55 &
done

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
