#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width        5
bspc config window_gap          8

bspc config split_ratio          0.50
bspc config single_monocle       true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color  "#000000"
# bspc config focused_border_color  "#ffff00"
bspc config focused_border_color  "#34a1eb"
bspc config presel_feedback_color "#C57E8700"

for i in {1..10}
do
  bspc desktop "$i" -l monocle
  # bsp-layout set tall "$i" -- --master-size 0.5 &
done

# bspc rule -a Alacritty:nvimlazygit center=on state=floating rectangle=1376x625+0+0
bspc rule -a Alacritty:ttyclock center=on state=floating rectangle=1376x625+0+0
bspc rule -a fzfcode center=on state=floating rectangle=1376x625+0+0
bspc rule -a fzfripgrepcode center=on state=floating rectangle=1376x625+0+0
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Firefox state=fullscreen
bspc rule -a GNvim state=tiled
bspc rule -a Zathura state=tiled
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
# bspc config external_rules_command /usr/local/bin/maxdesktops
# bspc subscribe node_remove | while read line; do
#     /usr/local/bin/backonempty
# done
