local api = vim.api
api.nvim_set_keymap( 'n',   '<A-`>', ':set relativenumber!<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-h>', 'i<space><esc>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-l>', 'a<space><esc>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-j>', ':m .+1<cr>==', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-k>', ':m .-2<cr>==', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-c>', ':bw<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-h>', ':bp<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-l>', ':bn<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-x>', ':bd!<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-t>', ':enew<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>1', ':enew<cr>:e ~/.config/nvim/lua/mappings.lua<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>2', ':enew<cr>:e ~/.config/nvim/lua/plugins.lua<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>3', ':enew<cr>:e ~/.config/nvim/lua/variables.lua<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>#', ':g/^\\s*$/d<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>b', ':Telescope buffers<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>e', ':NvimTreeToggle<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>f', ':Telescope find_files<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>h', ':noh<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>r', ':e!<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>s', ':update<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>S', ':bufdo wall<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<leader>x', ':bufdo bd!<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-b>', ':BufferPick<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-j>', 'o<esc>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-k>', 'O<esc>', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<C-y>', '^yg_', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-j>', '<esc>:m .+1<cr>==', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   '<A-k>', '<esc>:m .-2<cr>==', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   'C', '^i', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   'cw', 'ciw', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   'dw', 'diwx', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   'dW', 'diw', { noremap = true, silent = true })
api.nvim_set_keymap( 'n',   'X', ':%d<cr>', { noremap = true, silent = true })
api.nvim_set_keymap( 'i',   '<C-j>', '<esc>:m .+1<cr>==gi', { noremap = true, silent = true })
api.nvim_set_keymap( 'i',   '<C-k>', '<esc>:m .-2<cr>==gi', { noremap = true, silent = true })
api.nvim_set_keymap( 'v',   '<A-j>', ":m '>+1<cr>gv=gv", { noremap = true, silent = true })
api.nvim_set_keymap( 'v',   '<A-k>', ":m '<-2<cr>gv=gv", { noremap = true, silent = true })
api.nvim_set_keymap( 'v',   '<', '<gv', { noremap = true, silent = true })
api.nvim_set_keymap( 'v',   '>', '>gv', { noremap = true, silent = true })

