vim.g.mapleader = ' '
vim.o.background = 'dark'
vim.o.clipboard = 'unnamedplus'
vim.o.cursorline = true
vim.o.expandtab = true
vim.o.hidden = true
vim.o.ignorecase = true
vim.o.lazyredraw = true
vim.wo.wrap = false
vim.o.number = true
vim.o.smartcase = true
vim.o.scrolloff = 999
vim.o.smartindent = true
vim.o.smarttab = true
vim.o.tabstop = 4
vim.o.termguicolors = true
vim.o.updatetime = 300
vim.opt.shortmess = vim.opt.shortmess + 'c'
vim.o.completeopt = 'menuone,noinsert,noselect'
vim.wo.relativenumber = true
