#!/bin/bash

input_file=$1
python3 /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/xlsx2csv.py "$input_file" "/tmp/$input_file.csv"
csvlens "/tmp/$input_file.csv" && rm -f "/tmp/$input_file.csv"
