#!/bin/bash
args=("$@")
for i in "${args[@]}"
do
   : 
   FULLPATH=$(readlink -f $i)
   FILENAME=$(basename $i)
   DIRNAME=$(basename $(dirname $FULLPATH))
   cp -rfu $FULLPATH "$HOME/dotfiles/$DIRNAME/$FILENAME"
   # do whatever on $i
done
