#!/bin/bash

PROJECTDIR=/home/shlomo/workspace
LEN=${#PROJECTDIR}
cd $PROJECTDIR
COUNT=$(fd --type d -d 1 . $PROJECTDIR | wc -l)
SELECTED=$(fd --type d -d 1 . $PROJECTDIR | cut -c "$((LEN+2))"- | dmenu -l $COUNT)
[ "$SELECTED" = "" ] && exit 0
alacritty -e nvim $SELECTED
