#!/bin/bash

LASTDIR=/tmp/lastdir
PROJECTDIR=/home/shlomo/workspace
touch $LASTDIR
cd $PROJECTDIR
SELECTED=$(fd --type d -d 1 . $PROJECTDIR | fzf --cycle)
[ "$SELECTED" = "" ] && exit 0
echo $SELECTED > $LASTDIR
code $SELECTED
