#!/bin/bash

# export STARSHIP_CONFIG=~/.config/starship/config.toml
export PATH="~/bin:/usr/local/bin:/usr/local/lib/node_modules/bin:~/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:~/.dotnet/tools:~/Programs/fzf/bin"
xsetroot -cursor_name left_ptr &
clipmenud &
numlockx &
dunst &
setxkbmap us,il ,, grp:alt_shift_toggle &
# dwmblocks &
pgrep -x sxhkd > /dev/null || sxhkd &
# ~/.config/polybar/launch.sh &
~/.fehbg &
# xrander --output HDMI-2 --same-as eDP-1 &
# picom -bc &
mongod &
