local map = function(mode, key, value, opts)
	vim.api.nvim_set_keymap(mode, key, value, opts or { noremap = true, silent = true });
end

map('i', '<C-j>', 'v:lua.tab_complete()', {expr = true})
map('i', '<C-k>', 'v:lua.s_tab_complete()', {expr = true})
map('i', 'jj', '<esc>', opts)
map('n', '<A-b>', ':BufferLinePick<cr>', opts)
map('n', '<A-h>', ':BufferLineMovePrev<cr>', opts)
map('n', '<A-l>', ':BufferLineMoveNext<cr>', opts)
map('n', '<C-c>', ':bd<cr>', opts)
map('n', '<C-h>', ':BufferLineCyclePrev<cr>', opts)
map('n', '<C-j>', 'o<esc>', opts)
map('n', '<C-k>', 'O<esc>', opts)
map('n', '<C-l>', ':BufferLineCycleNext<cr>', opts)
map('n', '<C-p>', 'viwp', opts)
map('n', '<C-t>', ':enew<cr>', opts)
map('n', '<C-x>', ':bd!<cr>', opts)
map('n', '<C-y>', '^yg_', opts)
map('n', '<Tab>j', 'yyp', opts)
map('n', '<Tab>k', 'yyP', opts)
map('n', '<leader>S', ':wa<cr>', opts)
map('n', '<leader>b', ':Telescope buffers<cr>', opts)
map('n', '<leader>e', ':NvimTreeToggle<cr>', opts)
map('n', '<leader>f', ':Telescope find_files<cr>', opts)
map('n', '<leader>h', ':noh<cr>', opts)
map('n', '<leader>j', ':Lspsaga lsp_finder<cr>', opts)
map('n', '<leader>r', ':Lspsaga rename<cr>', opts)
map('n', '<leader>s', ':up<cr>', opts)
map('n', '<leader>x', ':bufdo bd<cr>', opts)
map('n', 'K', ':Lspsaga preview_definition<cr>', opts)
map('n', 'cw', 'ciw', opts)
map('n', 'dw', 'diwx', opts)
map('n', 'gD', ':lua vim.lsp.buf.declaration()<cr>', opts)
map('n', 'gd', ':lua vim.lsp.buf.definition()<cr>', opts)
map('n', 's', ':HopWord<cr>', opts)
map('s', '<C-j>', 'v:lua.tab_complete()', {expr = true})
map('s', '<C-k>', 'v:lua.s_tab_complete()', {expr = true})
