local map = function(mode, key, value, opts)
	vim.api.nvim_set_keymap(mode, key, value, opts or { noremap = true, silent = true });
end

map('i', '<cr>', "compe#confirm({ 'keys': '<cr>', 'select': v:true })", { expr = true })
map('i', '<C-j>', 'v:lua.tab_complete()', { expr = true })
map('i', '<C-k>', 'v:lua.s_tab_complete()', { expr = true })
map('i', 'jj', '<esc>')
map('n', '<A-b>', ':BufferLinePick<cr>')
map('n', '<A-u>', ':BufferLineMovePrev<cr>')
map('n', '<A-i>', ':BufferLineMoveNext<cr>')
map('n', '<C-c>', ':bd<cr>')
map('n', '<C-h>', ':BufferLineCyclePrev<cr>')
map('n', '<C-j>', 'o<esc>')
map('n', '<C-k>', 'O<esc>')
map('n', '<C-l>', ':BufferLineCycleNext<cr>')
map('n', '<C-p>', 'viwp')
map('n', '<C-s>', ":lua require('spectre').open()<CR>")
map('n', '<C-t>', ':enew<cr>')
map('n', '<C-x>', ':bd!<cr>')
map('n', '<C-y>', '^yg_')
map('n', '<A-h>', 'i<space><esc>')
map('n', '<Tab>j', 'yyp')
map('n', '<Tab>k', 'yyP')
map('n', '<A-l>', 'a<space><esc>')
map('n', '<leader>S', ':wa<cr>')
map('n', '<leader>b', ':Telescope buffers<cr>')
map('n', '<leader>e', ':NvimTreeToggle<cr>')
map('n', '<leader>f', ':Telescope find_files<cr>')
map('n', '<leader>h', ':noh<cr>')
map('n', '<leader>j', ':Lspsaga lsp_finder<cr>')
map('n', '<leader>r', ':Lspsaga rename<cr>')
map('n', '<leader>s', ':up<cr>')
map('n', '<leader>x', ':bufdo bd<cr>')
map('n', 'K', ':Lspsaga preview_definition<cr>')
map('n', 'cw', 'ciw')
map('n', 'dw', 'diwx')
map('n', 'gD', ':lua vim.lsp.buf.declaration()<cr>')
map('n', 'gd', ':lua vim.lsp.buf.definition()<cr>')
map('n', 's', ':HopWord<cr>')
map('s', '<C-j>', 'v:lua.tab_complete()', {expr = true})
map('s', '<C-k>', 'v:lua.s_tab_complete()', {expr = true})
